### ISSUE TITLE
MSG Frequency不安定

### ISSUE THREAD

**Issue by cretaceous-creature** [haraduka/jsk_imu_mini#5]
@haraduka 結構前の話なんですけど、
`rostopic echo /imu -w 5`　
をするとき、HZが不安定になる問題もう解決したか？

それは、seiral to USB IC FT232のlatency_timer設定の問題、
`cat /sys/bus/usb-serial/devices/ttyUSB0/latency_timer`
default 16ms, 
`echo 1 > /sys/bus/usb-serial/devices/ttyUSB0/latency_timer`

または、linux kernel 4.11以上 setserialを使えば
`sudo setserial /dev/ttyUSB* low_latency`

**Comment by haraduka** [comment]
それは解決していて, roslaunchと同時にsetserialするようにしてあります:)
